// ng-frontend/src/app/components/product-list/product-list.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { ProductService } from '../../services/product-service.service';
import { CommonModule } from '@angular/common';
import { ProductDescriptionComponent } from "../product-description/product-description.component";

@Component({
  selector: 'app-product-list',
  standalone: true,
  imports: [CommonModule, ProductDescriptionComponent],
  templateUrl: './product-list.component.html',
  styleUrl: './product-list.component.scss'
})
export class ProductListComponent implements OnInit {


  productList:any[] = []
  highlightedIitem:any = null
  @Output() selectedProduct:any = new EventEmitter<null>();


  constructor(private productService:ProductService){
  }
  async ngOnInit(): Promise<void> {
    await this.getProductList()

  }

  getProductList() {
    this.productService.getProductList().subscribe(
      (response) => {
        console.log(response)
        this.productList = response.productList
        console.log(this.productList)

      },
      (error) => console.error('Error from product-list : ' , error)
    )
  }

  onSelection(item:any) {
    this.highlightedIitem = item
    this.selectedProduct.emit(item.id)
  }


}

<div>
  <div>
    <aside
      id="default-sidebar"
      class="top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"
      aria-label="Sidebar"
    >
      <div
        class="h-full px-3 py-4 overflow-y-auto bg-white-50 dark:bg-gray-800 shadow-md"
      >
      <p class="text-2xl font-bold text-gray-900 dark:text-white mb-4">Product List</p>

      <ul className="space-y-2 font-medium">


          <li
            *ngFor="let product of productList"
            class="flex items-center p-2 text-lg text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
            (click)="onSelection(product)"  
            [class.bg-indigo-200] = "product === highlightedIitem"
          >
            {{ product.name }}
          </li>
        </ul>
      </div>
    </aside>
  </div>
</div>

// frontend/src/components/product-list.jsx
const ProductList = ({ products, selectProduct }) => {
  const handleClick = (product) => {
    selectProduct(product);
  };

  return (
    <div>
      <div>
        <aside
          id="default-sidebar"
          className="top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"
          aria-label="Sidebar"
        >
          <div className="h-full px-3 py-4 overflow-y-auto bg-white-50 dark:bg-gray-800 shadow-md">
            <ul className="space-y-2 font-medium">

            {products.map((product) => (
          <li className="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" key={product.id} onClick={() => handleClick(product)}>
            {product.name}
          </li>
        ))} 
            </ul>
          </div>
        </aside>
      </div>    
    </div>
  );
};

export default ProductList;
